### ISSUE TITLE
I am dumb

### ISSUE THREAD

**Issue by Finister-Finn** [luiscastilho/dungeoneering#3] opened 2021-06-04 01:51 UTC
I realize that I am probably just dumb, but when I download the win64 zip and unzip it, there appears to be no .exe file. What am I doing wrong? I could send you a screen shot of everything that unzips if that would help. I really appreciate your time (for my stupidity and for building this resource which I hope to use in my future games).

Jeremi

**Comment by luiscastilho** [comment] 2021-06-04 03:07
Hi there. Don't worry, let's try to solve your problem. Release files for Windows once unzipped should contain an structure like this:

```
dungeoneering-v1.1.2-win64/
├─ data/
├─ java/
├─ lib/
├─ source/
├─ ABOUT.txt
├─ CHANGELOG.txt
├─ dungeoneering.exe
├─ KNOWN_ISSUES.txt
├─ LICENSE.txt
└─ THIRD_PARTY_LICENSES.txt
```

Maybe you have an antivirus/security program that's deleting the EXE file once you unzip it? That would be my first guess. Try to temporarily disable any such program or maybe to whitelist the folder you will be using for dungeoneering. Note that you need to unzip everything for the application to work, don't try to run dungeoneering.exe from inside the ZIP file.

Let me know if this helps.

**Comment by Finister-Finn** [comment] 2021-06-05 18:52
Hi,

Thanks for the reply! I believe I unzipped everything correctly, and I see those names in the folder but not the file extensions. Nothing has a .* after it. Where dungeoneering.exe should be is just dungeoneering, but it has a black circle with a triangle in it (the "play" icon). If I double-click it, it turns my second screen gray and then black. I can't interact with it at that point. I tried using just a single screen and had to Ctrl+alt+delete out of it. 

![dungeoneering](https://user-images.githubusercontent.com/62857879/120902298-2b635b80-c605-11eb-81bf-9621d7118d50.PNG)

**Comment by luiscastilho** [comment] 2021-06-05 19:40
My bad, I forgot Windows hides file extensions by default. The dungeoneering file with the play icon is the EXE indeed.

It looks like the application doesn't finish loading for some reason, giving you just a black screen. Sorry about that. I will create a version with logging so we can see what's going on. I will let you know once it's available for download. Then you can run this new version and send me the log files it generates, please.

**Comment by Finister-Finn** [comment] 2021-06-05 20:40
Oh wow! Sounds great! Thanks for working with me on this!

**Comment by luiscastilho** [comment] 2021-06-06 22:50
Thanks for trying dungeoneering and for helping me fix this problem, whatever it may be!

I just released v1.1.3, that logs application debug information to a file. When you run `dungeoneering.exe`, a log directory should be created in the same folder, with a log file inside - `\log\dungeoneering.log`. Once the problem happens (black screen, application not finishing loading, maybe closing by itself after a few seconds), do the following to send me the logs, please:

1. Open `dungeoneering.log` in Notepad
2. Copy its contents, from first to last line
3. Open [pastebin.com](https://pastebin.com/) - it's a website used to store and share large text files
4. Paste the file contents you copied in the text field under "New Paste"
5. In the field "Paste Name / Title" give this paste a name - dungeoneering.log or whatever
6. Click on "Create New Paste"
7. Once it's created, copy the address shown in your browser address bar - it will be something like [https://pastebin.com/vUQ6Mt31](https://pastebin.com/vUQ6Mt31)
8. Send the address Pastebin generated for you so I can take a look at the logs

Let's hope this will help us understand what's going on! 🤞

**Comment by Finister-Finn** [comment] 2021-06-09 20:25
Finally got around to this today... here's the paste: https://pastebin.com/d3fVtTdq

**Comment by luiscastilho** [comment] 2021-06-09 21:29
Great! Thanks for the paste. Apparently dungeoneering is starting as it should. I was expecting some kind of initialization error.

And what happens in the application when you run it? Frozen in a black screen?

**Comment by Finister-Finn** [comment] 2021-06-09 21:34
It starts as a grey screen and then sometimes go to black. Today it stayed grey. I can move the mouse over it, but there is no way to interact with it. No icons or anything. I can only shut it down from task manager.

________________________________

**Comment by Bazzatron19** [comment] 2021-06-23 08:59
Hi @luiscastilho, I've also got the grey screen issue.

I've completed the pastebin steps above - but it looks much the same, like nothing it really going wrong...
https://pastebin.com/VR0KQt45

Of note, the screen is wholly grey, and seems to prefer being always visible (i.e. on top of all other windows, regardless of what I do) and fullscreen (no options to shrink the edges).

Very rarely, I hover over some interactive object - and the cursor becomes a pointer, but I haven't been able to replicate for a screenshot. Otherwise it just looks like this:

![image](https://user-images.githubusercontent.com/53759374/123068033-6fc66800-d409-11eb-8078-49b3f90facb1.png)

**Comment by luiscastilho** [comment] 2021-06-24 23:15
Hi @Finister-Finn, @Bazzatron19,

Sorry for the late reply. Creating a version for Linux and macOS took a lot longer than I thought it would. But with that out of the way we can focus on debugging this problem now. The main issue for me is not being able to reproduce this problem on my machine. So I will need more info from you, please, in order to try to reproduce this problem here.

1. First try the latest version of dungeoneering ([v1.2.0](https://github.com/luiscastilho/dungeoneering/releases/latest/download/dungeoneering-windows64.zip)) just to make sure the problem still occurs. I believe it will but it's a good first test.

2. What version of Windows are you using? You can check that by right clicking on the Start Menu (Windows logo on the bottom left corner) and choosing System. It will open an About page and there you will see a Windows Specification section with a Copy button right below it. Mine is:

```
Edition: Windows 10 Pro
Version: 21H1
Installed on: 2020-08-16
OS build: 19043.1081
Experience: Windows Feature Experience Pack 120.2212.3530.0
```

3. Where was dungeoneering unzipped? The full path I mean. Mine is at `C:\Users\Luis\Documents\dungeoneering-windows64`.

4. And one last thing. Open the dungeoneering folder on File Explorer, hold Shift, right click anywhere on this folder and choose "Open PowerShell window here". On PowerShell type `tree /F`. It will list all dungeoneering files and folders. Paste the PowerShell output in Pastebin and send it to me please. Here's the output I get when I run this command: https://pastebin.com/yyPsYWcu

Thanks for helping me debug this!

**Comment by Bazzatron19** [comment] 2021-06-28 12:02
Hi @luiscastilho!

It's not a problem, thanks for your continued efforts...!

Running v1.2.0 results in the same issue for me. Fullscreen solid grey. Nothing is interactable (apologies for that crap screenshot, that'll teach me for not checking the image before hitting submit! Apparently my screenshot just sees right through the application (probably because it's drawn over top of everything?)

Log for v1.2.0 doesn't really show anything different than the pastebin I posted previously. No obvious errors.

My system is:

```Edition	Windows 10 Home
Version	20H2
Installed on	‎17/‎08/‎2020
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
```

So far as windows updates go, it's all up to date - I just haven't jumped to the 21H1 feature set, which I might roll out tonight.

You didn't ask but FWIW - specs, we've got:

```
CPU: AMD FX-8150
RAM: 12GB 
GPU: RX Vega (Using Radeon drivers 21.2.1)
```

(Yes, I am aware it's a cobbled together mess...!)

Full path for the extract is `C:\Users\James\Downloads\dungeoneering-windows64`.
I've also tried dumping the whole folder into `c:\dunge` just to see if it was a long filepath or character causing an issue.

I've also tried running as admin, but just seems like nothing wants to draw save for the grey bg layer.

I've dumped the tree to: https://pastebin.com/LuFuwSKN

**Comment by Bazzatron19** [comment] 2021-07-01 09:56
Hi again @luiscastilho 

Though I'd just dip my toe back in and run some older versions to see what's up.
I launched v1.0.0 and it actually runs.

I'm just going to download and run each version - and hopefully that'll highlight a particular change that might narrow down our testing.

**Comment by luiscastilho** [comment] 2021-07-02 02:24
Hey @Bazzatron19,

Glad you managed to fing a version that runs on your machine! Let me know since which version you get the dreaded grey screen. It might help narrow down our testing indeed.

I'm suspecting Processing (the IDE/language I used to develop dungeoneering) might be throwing some error that's not being logged to dungeoneering log file. When you get a chance create a `dungeoneering.bat` file inside the same folder where `dungeoneering.exe` is, with the following content:

```
@echo off
%~dp0\java\bin\java.exe -Djava.ext.dirs=lib -Djava.library.path=lib dungeoneering
```

Then open a PowerShell in this folder (open the dungeoneering folder on File Explorer, hold Shift, right click anywhere on this folder and choose "Open PowerShell window here"), type `.\dungeoneering.bat` and press Enter. You should see an output like the one below, hopefully with some error that might explain why you are seeing a grey screen and not dungeoneering user interface.

```
PS C:\Users\Luis\Documents\dungeoneering-windows64> .\dungeoneering.bat
Display 2 does not exist, using the default display instead.
Display 1 is D3DGraphicsDevice[screen=0]
[2021-07-01 23:12:25] INFO: Logger: Log level set to DEBUG
[2021-07-01 23:12:25] INFO: Setup: dungeoneering initialization started
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
[2021-07-01 23:12:25] DEBUG: Setup: controlP5 initialization done
[2021-07-01 23:12:25] DEBUG: Setup: canvases initialization done
[2021-07-01 23:12:25] DEBUG: Setup: obstacles initialization done
[2021-07-01 23:12:25] DEBUG: Setup: map initialization done
[2021-07-01 23:12:25] DEBUG: Setup: grid initialization done
[2021-07-01 23:12:25] DEBUG: Setup: initiative initialization done
[2021-07-01 23:12:25] DEBUG: Setup: resources initialization done
[2021-07-01 23:12:25] DEBUG: Setup: layers initialization done
[2021-07-01 23:12:25] DEBUG: Setup: UI controllers setup started
[2021-07-01 23:12:25] DEBUG: Setup: UI controllers setup done
[2021-07-01 23:12:25] DEBUG: Setup: UI initialization done
[2021-07-01 23:12:25] INFO: Setup: dungeoneering initialization done
```

Fingers crossed! 🤞

**Comment by Bazzatron19** [comment] 2021-07-02 11:46
Hey @luiscastilho,

As soon as I read `display 2 does not exist` in your log, my suspicion was piqued.

I haven't yet run through all versions of dungeoneering - but I'll do that today.

Something my spec didn't allude to - I have 4x monitors (I'm a Salesforce developer, before you get any RGB ideas about my setup..! But do please feel free to judge me! 😉)
![image](https://user-images.githubusercontent.com/53759374/124269917-6b016280-db33-11eb-816e-bd9545978233.png)


v1.0.0 opens on monitor 2, whereas the most recent version prefers monitor 1.

Anyway, I ran your script with v1.2.0, and this is the output:

```
PS C:\dunge> .\dungeoneering.bat
[2021-07-02 12:35:41] INFO: Logger: Log level set to DEBUG
[2021-07-02 12:35:41] INFO: Setup: dungeoneering initialization started
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
[2021-07-02 12:35:41] DEBUG: Setup: controlP5 initialization done
[2021-07-02 12:35:41] DEBUG: Setup: canvases initialization done
java.lang.RuntimeException: Waited 5000ms for: <3eca1f81, 300df628>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
        at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:410)
        at java.lang.Thread.run(Thread.java:748)
[2021-07-02 12:35:47] DEBUG: Setup: obstacles initialization done
[2021-07-02 12:35:47] DEBUG: Setup: map initialization done
[2021-07-02 12:35:47] DEBUG: Setup: grid initialization done
[2021-07-02 12:35:47] DEBUG: Setup: initiative initialization done
[2021-07-02 12:35:47] DEBUG: Setup: resources initialization done
[2021-07-02 12:35:47] DEBUG: Setup: layers initialization done
[2021-07-02 12:35:47] DEBUG: Setup: UI controllers setup started
[2021-07-02 12:35:48] DEBUG: Setup: UI controllers setup done
[2021-07-02 12:35:48] DEBUG: Setup: UI initialization done
[2021-07-02 12:35:48] INFO: Setup: dungeoneering initialization done
```

FWIW, I checked my java version, ran the installer for the latest JRE and the log changed only in the timestamp.

Hopefully that JRexception points you to something useful..!

**Comment by Bazzatron19** [comment] 2021-07-02 12:09
Okay....

So I opened each version, and I tried to open the following map file where dungeoneering would run
https://imgur.com/vMtFxBm

Sadly, I  hit the grey screen pretty quickly.


**v1.0.1**
Opens, seems to run fine. Prefers screen 2
Either takes a long time (>2mins) to load the file, or doesn't load it at all - clicking the X button crashed the application, and I had to kill javaw in details on taskmgr.


**v1.0.2**
Loads into grey screen. Prefers screen 2
App not responsive to Alt+F4 and drew over top of the taskbar, had to kill with taskmgr again.

**v1.1.0**
Loads into grey screen. Prefers screen 2
App not responsive to Alt+F4 and drew over top of the taskbar, had to kill with taskmgr again.

**v1.1.1**
Loads into grey screen. Prefers screen 2
App not responsive to Alt+F4 and drew over top of the taskbar, had to kill with taskmgr again.

**v1.1.2**
Loads into grey screen. Prefers screen 1
App not responsive to Alt+F4 and drew over top of the taskbar, had to kill with taskmgr again.

**v1.1.3**
Loads into grey screen. Prefers screen 1
App not responsive to Alt+F4 and drew over top of the taskbar, had to kill with taskmgr again.

**Comment by luiscastilho** [comment] 2021-07-02 14:58
Not sure how to fix it yet but I'm quite sure we found the culprit. I will try to reproduce this error during the weekend.

```
java.lang.RuntimeException: Waited 5000ms for: <3eca1f81, 300df628>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
        at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:410)
        at java.lang.Thread.run(Thread.java:748)
```

I will also check what changed from version 1.0.0 to versions 1.0.1 and 1.0.2.

Thanks again for your help!

**Comment by luiscastilho** [comment] 2021-07-04 17:42
Hey @Bazzatron19, @Finister-Finn,

Can you guys test the version below please? I managed to reproduce the problem and I believe I fixed it. If dungeoneering setup didn't finish in 5s or less, Processing would throw a (hidden) exception and dungeoneering would get stuck in a grey screen. I moved some lines of code in setup to try to avoid this problem. Let me know if this version works for you please.

https://github.com/luiscastilho/dungeoneering/releases/download/v1.2.1/dungeoneering-windows64.zip

Thanks!

**Comment by Bazzatron19** [comment] 2021-07-05 12:03
@luiscastilho 

You absolute champion. I get a lot of screen flickering (like when a fullscreen app loads up really) but it does launch!
Now I just need to figure out how to use this application! I've already managed to PEBCAK my way into one issue that throws the following error in the log:

```
[2021-07-05 12:54:12] ERROR: java.lang.RuntimeException: A JSONObject text must begin with '{'
	at processing.data.JSONObject.<init>(JSONObject.java:242)
	at processing.data.JSONObject.<init>(JSONObject.java:226)
	at processing.core.PApplet.loadJSONObject(PApplet.java:6088)
	at dungeoneering$UserInterface.loadScene(dungeoneering.java:6658)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet.selectCallback(PApplet.java:6719)
	at processing.core.PApplet.access$1(PApplet.java:6712)
	at processing.core.PApplet$4.run(PApplet.java:6623)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

But that's just what happens when you select a PNG instead of a json when using the "Load scene" button.

I'd give v1.2.1 the seal of approval, but I don't know enough to QA it yet!

Curious that it didn't replicate for you - presumably you're running a much better machine than me! :)

**Comment by luiscastilho** [comment] 2021-07-05 16:29
Hey @Bazzatron19,

I'm really glad this version worked for you! :)

I will add some defensive code when loading a scene, to check if it's indeed a JSON. In the not-so-distant future I want to move all tokens, maps and scenes to inside the application, so users won't need to switch between the application and the OS filesystem all the time. It would be nice to have some UI element showing all relevant assets, with a little preview and everything. But first I will keep working on having a DM and a players' version, both interacting with the same scene. That's something I missed when I used dungeoneering as a DM.

About how to use the application, this might help: https://luiscastilho.github.io/dungeoneering/#how-to-use-it
And there's a video showing how to create a scene: https://www.youtube.com/watch?v=mLLleHoVkdk
I should probably link this video in dungeoneering main page.

It's indeed curious that this problem didn't happen on my machine. Here's what I have:

```
CPU: Intel i7-4790
RAM: 16GB
GPU: GeForce GTX 970 4GB
```

But it's working now and that's all that matters. :)

Closing this issue for now. Let me know if I can help you with anything else. :+1:

**Closed** 2021-07-05 16:41 UTC
Labels: bug, support
